version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: balabank_db # Я вернул имя как в твоем логе
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: family_db
    volumes:
      - db_data:/var/lib/postgresql/data # <--- ВАЖНО: теперь тут не путь, а имя

# Это новая секция в самом низу файла
volumes:
  db_data: